
flib_version=1.0.0-SNAPSHOT

mod_id=heartbalance
curse_slug=heart-balance
curse_id=465049
mod_version=1.0.3
mod_name=heartbalance
mod_group_id=com.lothrazar.heartbalance
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
